### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by Anoaxx** [DeathsGun/ModManager#27]
Game crash after trying to open mod screen by clicking button in modmenu screen

 - OS: Windows 10
 - Minecraft version 1.17.1
 - Version 1.0.0-alpha

Latest log:

Description: mouseClicked event handler

java.lang.AbstractMethodError: Receiver class xyz.deathsgun.modmanager.gui.ModsOverviewScreen does not define or inherit an implementation of the resolved method 'abstract net.minecraft.class_364 getFocused()' of interface xyz.deathsgun.modmanager.gui.widget.better.IListScreen.
	at Not Enough Crashes deobfuscated stack trace.(1.17.1+build.35)
	at xyz.deathsgun.modmanager.gui.widget.better.BetterListWidget.isFocused(BetterListWidget.java:52)
	at net.minecraft.client.gui.widget.EntryListWidget.getType(EntryListWidget:541)
	at net.minecraft.client.gui.screen.Screen.findSelectedElementData(Screen:603)
	at net.minecraft.client.gui.screen.Screen.addElementNarrations(Screen:581)
	at net.minecraft.client.gui.screen.Screen.addScreenNarrations(Screen:576)
	at net.minecraft.client.gui.screen.narration.ScreenNarrator.buildNarrations(ScreenNarrator:34)
	at net.minecraft.client.gui.screen.Screen.narrateScreen(Screen:566)
	at net.minecraft.client.gui.screen.Screen.narrateScreenIfNarrationEnabled(Screen:561)
	at net.minecraft.client.gui.screen.Screen.init(Screen:388)
	at net.minecraft.client.MinecraftClient.setScreen(MinecraftClient:984)
	at com.terraformersmc.modmenu.gui.ModsScreen.md03617e$lambda$onInit$0$0(ModsScreen.java:594)
	at net.minecraft.client.gui.widget.ButtonWidget.onPress(ButtonWidget:40)
	at net.minecraft.client.gui.widget.PressableWidget.onClick(PressableWidget:16)
	at net.minecraft.client.gui.widget.ClickableWidget.mouseClicked(ClickableWidget:121)
	at net.minecraft.client.gui.ParentElement.mouseClicked(ParentElement:27)
	at net.minecraft.client.Mouse.method_1611(Mouse:94)
	at net.minecraft.client.gui.screen.Screen.wrapScreenError(Screen:490)
	at net.minecraft.client.Mouse.onMouseButton(Mouse:94)
	at net.minecraft.client.Mouse.method_22686(Mouse:165)
	at net.minecraft.util.thread.ThreadExecutor.execute(ThreadExecutor:101)
	at net.minecraft.client.Mouse.method_22684(Mouse:165)
	at org.lwjgl.glfw.GLFWMouseButtonCallbackI.callback(GLFWMouseButtonCallbackI.java:36)
	at org.lwjgl.system.JNI.invokeV(Native Method)
	at org.lwjgl.glfw.GLFW.glfwPollEvents(GLFW.java:3101)
	at com.mojang.blaze3d.systems.RenderSystem.flipFrame(RenderSystem:165)
	at net.minecraft.client.util.Window.swapBuffers(Window:310)
	at net.minecraft.client.MinecraftClient.render(MinecraftClient:1137)
	at net.minecraft.client.MinecraftClient.run(MinecraftClient:728)
	at net.minecraft.client.main.Main.main(Main:217)
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:567)
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:234)
	at net.fabricmc.loader.launch.knot.Knot.launch(Knot.java:153)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:28)
(if you want entire crashlog i can paste it here)

**Additional context**
I have a blame mod that tells me thats possible crash is happened because ModMenager, ModMenu and/or FabricLoader. Im suppose that ModMenu i FabricLoader works fine until i install this mod. I have several mods. if you want to see: 
![image](https://user-images.githubusercontent.com/64927564/130666605-dc783855-e52a-4a73-aaff-944705cc1840.png)

**Comment by DeathsGun** [comment]
Thanks for reporting!

This bug was fixed in the new version [1.0.1+1.17.1-alpha](https://modrinth.com/mod/modmanager/version/gGSLHqJK)

**Comment by Anoaxx** [comment]
i try my best :')

**Comment by Anoaxx** [comment]
btw you gonna add curseforge to mod because some of my mods are from here.

**Comment by DeathsGun** [comment]
Sorry but unless Curseforge makes their API official I will not support them, but ModManager has an API which allows others to implement their own providers. So if somebody wants to implement Curseforge support I will not stop them and I will merge it but I'm not to keen on supporting an unofficial API.
In the mean time you could ask your mod author to upload them to Modrinth.

**Comment by Anoaxx** [comment]
can i catch you somewhere becouse i have some questions and ideas for you and i dont wanna spitting garbage on your issue tab

**Comment by DeathsGun** [comment]
On discord: DeathsGun#2539
