### ISSUE TITLE
[BUG] Downloading just doesn't work every time.

### ISSUE THREAD

**Issue by DeJayDev** [DeathsGun/ModManager#61]
**Describe the bug**
Some mods (in my experience, ModMenu and LibZoomer) cannot be updated with this tool. I've successfully updated MouseWheelie so I know it's not completely busted.

**To Reproduce**
1. While running an outdated ModMenu (I am on `modmenu-2.0.5.jar`)
1. Running open ModMenu
2. Click on the update icon
3. Attempt to update ModMenu

**Expected behavior**
The mod updates silently and the menu is closed.

** Please complete the following information:**
 - OS: Pop!_OS
 - Minecraft Version: 1.17.1
 - ModManager Version: 1.0.2+1.17-alpha

** Logs **
```
Error while executing task for modmenu
java.lang.NullPointerException: Cannot invoke "String.equals(Object)" because the return value of "xyz.deathsgun.modmanager.model.ReducedModMetadata.getName()" is null
	at xyz.deathsgun.modmanager.util.FabricMods.getJarFromModContainer(FabricMods.java:57) ~[modmanager-1.0.2+1.17-alpha.jar:?]
	at xyz.deathsgun.modmanager.tasks.ModUpdateTask.execute(ModUpdateTask.java:38) ~[modmanager-1.0.2+1.17-alpha.jar:?]
	at xyz.deathsgun.modmanager.api.manipulation.ManipulationTask.executeTask(ManipulationTask.java:47) [modmanager-1.0.2+1.17-alpha.jar:?]
	at xyz.deathsgun.modmanager.services.ManipulationService.run(ManipulationService.java:49) [modmanager-1.0.2+1.17-alpha.jar:?]
```

**Comment by DeathsGun** [comment]
v1.1.0+1.17-alpha should fix this as it's a complete rewrite of ModManager. I will provide a test version tomorrow.

**Comment by DeathsGun** [comment]
Here you go:
[modmanager-1.1.0+1.17-alpha.jar.zip](https://github.com/DeathsGun/ModManager/files/7229605/modmanager-1.1.0%2B1.17-alpha.jar.zip)

**Comment by DeJayDev** [comment]
Works! Thanks.
