### ISSUE TITLE
[BUG] Wrong version of mod downloaded

### ISSUE THREAD

**Issue by keatit71** [DeathsGun/ModManager#67]
**Describe the bug**
Wrong version of mod is downloaded

**To Reproduce**
1. Update mod
2. Realise wrong mod version was downloaded

**Expected behavior**
Should have downloaded the right version for 1.17.1

**Screenshots**

** Please complete the following information:**
 - OS: Windows 10
 - Minecraft version 1.17.1
 - Version Latest

** Logs **
Latest log:
[16:58:05] [main/INFO]: Loading for game Minecraft 1.17.1
[16:58:06] [ForkJoinPool-1-worker-7/WARN]: The mod "harvest" contains invalid entries in its mod json:
- Unsupported root entry "links" at line 7 column 10
[16:58:06] [ForkJoinPool-1-worker-3/WARN]: Non-Fabric mod JAR at "D:\Games\MultiMC\instances\1.17.1\.minecraft\mods\illuminations-uninstaller.jar", ignoring
[16:58:07] [main/FATAL]: A critical error occurred
net.fabricmc.loader.discovery.ModResolutionException: Could not find required mod: detailab requires {minecraft @ [1.16.x]}
	at net.fabricmc.loader.discovery.ModResolver.findCompatibleSet(ModResolver.java:198) ~[fabric-loader-0.11.6.jar:?]
	at net.fabricmc.loader.discovery.ModResolver.resolve(ModResolver.java:832) ~[fabric-loader-0.11.6.jar:?]
	at net.fabricmc.loader.FabricLoader.setup(FabricLoader.java:195) ~[fabric-loader-0.11.6.jar:?]
	at net.fabricmc.loader.FabricLoader.load(FabricLoader.java:185) [fabric-loader-0.11.6.jar:?]
	at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:132) [fabric-loader-0.11.6.jar:?]
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:28) [fabric-loader-0.11.6.jar:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:567) ~[?:?]
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:210) [NewLaunch.jar:?]
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:245) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.listen(EntryPoint.java:143) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.main(EntryPoint.java:34) [NewLaunch.jar:?]
Caused by: net.fabricmc.loader.util.sat4j.specs.ContradictionException: Creating Empty clause ?
	at net.fabricmc.loader.util.sat4j.minisat.constraints.cnf.Clauses.propagationCheck(Clauses.java:117) ~[fabric-loader-sat4j-2.3.5.4.jar:?]
	at net.fabricmc.loader.util.sat4j.minisat.constraints.cnf.Clauses.sanityCheck(Clauses.java:97) ~[fabric-loader-sat4j-2.3.5.4.jar:?]
	at net.fabricmc.loader.util.sat4j.minisat.constraints.MixedDataStructureDanielWL.createClause(MixedDataStructureDanielWL.java:81) ~[fabric-loader-sat4j-2.3.5.4.jar:?]
	at net.fabricmc.loader.util.sat4j.minisat.core.Solver.addClause(Solver.java:401) ~[fabric-loader-sat4j-2.3.5.4.jar:?]
	at net.fabricmc.loader.discovery.ModResolver.findCompatibleSet(ModResolver.java:195) ~[fabric-loader-0.11.6.jar:?]
	... 13 more

**Comment by DeathsGun** [comment]
Can you give me the name of the mod you have downloaded via ModManager

**Comment by keatit71** [comment]
The mod was detail armor bar

**Comment by DeathsGun** [comment]
Oke i found the error detail armor bar links multiple jars with fabric, forge and for 1.16 and for 1.17. I will fix that now

**Comment by DeathsGun** [comment]
Does this version fix your problem?

[modmanager-1.1.0-alpha+1.17.jar.zip](https://github.com/DeathsGun/ModManager/files/7271433/modmanager-1.1.0-alpha%2B1.17.jar.zip)

**Comment by keatit71** [comment]
That did fix it, though there's no an issue with updating bedrockify.

Also i think you should make this a program rather than a mod if you can since it would allow for deleting old mod versions

**Comment by DeathsGun** [comment]
Oh I'm currently thinking for a solution there no need to make this a standalone program

**Comment by keatit71** [comment]
what about the issue with bedrockify?

**Comment by DeathsGun** [comment]
Fixed with #70
